/**
 * First-draft generation via email (Section 4).
 *
 * For a `draft_document` intent, Zane produces a playbook-grounded first draft.
 * SCOPED for now to: NDA (mutual / one-way), basic services agreement, and a
 * simple variation/extension letter. Out-of-scope requests get a clear reply
 * pointing them at the review flow instead.
 *
 * The draft is built with ONE Claude Sonnet 4.6 call that is hard-constrained to
 * the company's PREFERRED playbook positions, never invents commercial terms,
 * and marks every business decision as [TO CONFIRM: ...]. Output is a clean DOCX
 * attached to the reply and stored in the Library (draft: true, source: email).
 */

import fs from "fs";
import path from "path";
import { nanoid } from "nanoid";
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from "docx";
import { pb } from "../pb.js";
import { llmJsonCall } from "./llmJsonParse.js";
import { getModelForTask } from "./modelRouter.js";
import { ensureInboundSchema } from "./inboundEmail.js";
import { threadReplyText, threadReplyHtml, linkThreadContract, type ThreadContext } from "./emailThreads.js";
import { buildCounterpartyProfile, profileDraftToConfirm } from "./counterpartyProfile.js";
import { audit } from "./auditLogger.js";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type PBRecord = Record<string, any>;

const APP_URL = process.env.APP_URL ?? "http://localhost:3000";

interface IntentParams {
  counterparty?: string;
  documentType?: string;
  ourRole?: string;
  instructions?: string;
}

// ─── Scope ─────────────────────────────────────────────────────────────────────

type DraftType = "NDA_MUTUAL" | "NDA_ONEWAY" | "SERVICES_AGREEMENT" | "VARIATION_LETTER";

const DRAFT_TYPE_LABEL: Record<DraftType, string> = {
  NDA_MUTUAL: "Mutual Non-Disclosure Agreement",
  NDA_ONEWAY: "One-Way Non-Disclosure Agreement",
  SERVICES_AGREEMENT: "Services Agreement",
  VARIATION_LETTER: "Variation Letter",
};

const DRAFT_TYPE_CONTRACTTYPE: Record<DraftType, string> = {
  NDA_MUTUAL: "NDA",
  NDA_ONEWAY: "NDA",
  SERVICES_AGREEMENT: "MSA",
  VARIATION_LETTER: "OTHER",
};

/** Map the requested document type (+ instructions) to an in-scope draft type, or null. */
export function classifyDraftType(documentType?: string, instructions?: string): DraftType | null {
  const t = `${documentType ?? ""} ${instructions ?? ""}`.toLowerCase();
  if (/variation|deed of variation|extension letter|extension of|amendment letter|side letter|vary the|extend the/.test(t)) {
    return "VARIATION_LETTER";
  }
  if (/\bnda\b|non.?disclosure|confidentiality agreement/.test(t)) {
    return /one.?way|unilateral|one.?direction/.test(t) ? "NDA_ONEWAY" : "NDA_MUTUAL";
  }
  if (/services agreement|services contract|\bmsa\b|master services|consultancy agreement|statement of work|\bsow\b/.test(t)) {
    return "SERVICES_AGREEMENT";
  }
  return null;
}

// ─── Draft content (single Sonnet call) ───────────────────────────────────────

const FOOTER_TEXT = (companyName: string) =>
  `First draft generated by Zane from ${companyName}'s playbook. For review before use, not legal advice.`;

interface DraftContent {
  title: string;
  intro: string;
  clauses: Array<{ heading: string; body: string }>;
  keyPositions: string[];
  toConfirm: string[];
}

const clauseLabel = (c: string) => (c ?? "").replace(/_/g, " ").toLowerCase().replace(/\b\w/g, (x) => x.toUpperCase());

async function generateDraftContent(opts: {
  draftType: DraftType;
  companyName: string;
  sector: string;
  governingLaw: string;
  counterparty: string;
  instructions: string;
  playbookRules: PBRecord[];
  model: string;
}): Promise<DraftContent> {
  const { draftType, companyName, sector, governingLaw, counterparty, instructions, playbookRules, model } = opts;

  const positionsBlock = playbookRules.length > 0
    ? playbookRules.map((r) => `- ${clauseLabel(r["clauseCategory"] as string)}: ${r["preferredPosition"] ?? ""}`).join("\n")
    : "(No playbook positions on file. Use balanced, standard market positions and mark anything material as [TO CONFIRM].)";

  const cp = counterparty || "[TO CONFIRM: counterparty name]";

  const system = `You are Zane, drafting a FIRST DRAFT of a ${DRAFT_TYPE_LABEL[draftType]} for ${companyName} (${sector} sector). The draft takes ${companyName}'s PREFERRED position on every clause. Respond with JSON only.

HARD RULES (follow exactly):
1. Only use the playbook positions provided below. Do NOT introduce positions, protections, or obligations that are not grounded in them or in standard, non-controversial boilerplate for this document type.
2. Mark anything that requires a business decision as "[TO CONFIRM: <what to confirm>]" inline in the clause text (e.g. term length, fee amounts, scope of services, notice periods if not in the playbook).
3. NEVER invent commercial terms, prices, fees, dates, quantities, durations, volumes, that were not given. Use a [TO CONFIRM: ...] placeholder instead.
4. Governing law is ${governingLaw}. Use ${companyName} and ${cp} as the parties.
5. Produce a complete, usable, professionally drafted document with numbered clauses.`;

  const user = `Draft a ${DRAFT_TYPE_LABEL[draftType]}.

PARTIES: ${companyName} and ${cp}
GOVERNING LAW: ${governingLaw}
${instructions ? `SPECIFIC INSTRUCTIONS FROM THE USER: ${instructions}\n` : ""}
${companyName}'S PLAYBOOK, PREFERRED POSITIONS (take these positions in the draft):
${positionsBlock}

Return ONLY this JSON:
{
  "title": "the document title",
  "intro": "the opening / parties / recital paragraph(s) as plain text",
  "clauses": [
    { "heading": "1. Clause heading", "body": "the full clause text; use [TO CONFIRM: ...] for any business decision" }
  ],
  "keyPositions": ["3 short bullets summarising the key playbook positions this draft takes"],
  "toConfirm": ["every distinct item you marked TO CONFIRM, as a short list"]
}

Make it a real, complete draft, not an outline. For a variation/extension letter, format it as a short letter that references "[TO CONFIRM: the underlying agreement and its date]".`;

  const raw = await llmJsonCall<Record<string, unknown>>({
    messages: [
      { role: "system", content: system },
      { role: "user", content: user },
    ],
    model,
    maxTokens: 8000,
    timeoutMs: 120_000,
    description: `first-draft generation (${draftType})`,
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const r = raw as any;
  const clauses = Array.isArray(r.clauses)
    ? r.clauses
        .filter((c: unknown) => c && typeof c === "object")
        .map((c: PBRecord) => ({ heading: String(c.heading ?? "").trim(), body: String(c.body ?? "").trim() }))
        .filter((c: { heading: string; body: string }) => c.heading || c.body)
    : [];
  return {
    title: String(r.title ?? DRAFT_TYPE_LABEL[draftType]).trim(),
    intro: String(r.intro ?? "").trim(),
    clauses,
    keyPositions: Array.isArray(r.keyPositions) ? r.keyPositions.map((x: unknown) => String(x).trim()).filter(Boolean).slice(0, 3) : [],
    toConfirm: Array.isArray(r.toConfirm) ? r.toConfirm.map((x: unknown) => String(x).trim()).filter(Boolean) : [],
  };
}

// ─── DOCX rendering ────────────────────────────────────────────────────────────

function bodyToParagraphs(body: string): Paragraph[] {
  return body.split(/\n+/).map((line) => new Paragraph({ text: line.trim(), spacing: { after: 120 } }))
    .filter((_, i, arr) => arr.length > 0);
}

async function renderDocx(content: DraftContent, companyName: string): Promise<Buffer> {
  const children: Paragraph[] = [];
  children.push(new Paragraph({ text: content.title, heading: HeadingLevel.TITLE, spacing: { after: 240 } }));
  if (content.intro) {
    for (const p of content.intro.split(/\n+/)) {
      if (p.trim()) children.push(new Paragraph({ text: p.trim(), spacing: { after: 160 } }));
    }
  }
  for (const clause of content.clauses) {
    if (clause.heading) {
      children.push(new Paragraph({
        children: [new TextRun({ text: clause.heading, bold: true })],
        spacing: { before: 200, after: 80 },
      }));
    }
    children.push(...bodyToParagraphs(clause.body));
  }
  // Footer (4d)
  children.push(new Paragraph({
    spacing: { before: 360 },
    children: [new TextRun({ text: FOOTER_TEXT(companyName), italics: true, size: 18, color: "64748B" })],
  }));

  const doc = new Document({ sections: [{ properties: {}, children }] });
  return Packer.toBuffer(doc);
}

// ─── Orchestration ─────────────────────────────────────────────────────────────

export async function processDraftByEmail(input: {
  company: PBRecord;
  sender: string;
  subject: string;
  messageId: string;
  intentParams: IntentParams;
  inboundRecordId: string;
  threadId?: string;
}): Promise<void> {
  const { company, sender, subject, messageId, intentParams, inboundRecordId } = input;
  const fromAddr = (company["inbound_email"] as string) || undefined;
  const replySubject = subject ? `Re: ${subject}` : "Your first draft";
  const companyName = ((company["name"] as string) ?? "").trim() || "Your company";
  const threadId = input.threadId ?? "";
  const ctx = (contractId?: string): ThreadContext => ({
    companyId: company.id as string, user: sender, threadId, intent: "draft_document", contractId,
  });

  // 4a. Scope check.
  const draftType = classifyDraftType(intentParams.documentType, intentParams.instructions);
  if (!draftType) {
    const requested = intentParams.documentType?.trim() || "that document";
    await threadReplyText(ctx(), {
      to: sender, from: fromAddr, subject: replySubject, inReplyTo: messageId,
      text: `First drafts are currently available for NDAs, services agreements, and variation letters. For ${requested} I can review a counterparty draft instead, just forward it to me.\n\nZane`,
    });
    if (inboundRecordId) await pb.collection("inbound_emails").update(inboundRecordId, { status: "OUT_OF_SCOPE" }).catch(() => {});
    console.log(`[draft] out of scope (${requested}) for ${sender}`);
    return;
  }

  await ensureInboundSchema().catch(() => {});
  const model = getModelForTask("playbook_comparison"); // Claude Sonnet 4.6
  const governingLaw = (company["jurisdiction"] as string) || "England & Wales";

  const playbookRules = await pb.collection("playbook_rules")
    .getFullList({ filter: `company = "${company.id}"` }).catch(() => [] as PBRecord[]);

  let content: DraftContent;
  try {
    content = await generateDraftContent({
      draftType,
      companyName,
      sector: (company["sector"] as string) || "",
      governingLaw,
      counterparty: intentParams.counterparty ?? "",
      instructions: intentParams.instructions ?? "",
      playbookRules,
      model,
    });
  } catch (err) {
    console.error(`[draft] generation failed for ${sender}:`, (err as Error)?.message);
    await threadReplyText(ctx(), {
      to: sender, from: fromAddr, subject: replySubject, inReplyTo: messageId,
      text: `Sorry, I couldn't generate that draft just now. Please try again or contact ahmed@zanelegal.ai.\n\nZane`,
    });
    if (inboundRecordId) await pb.collection("inbound_emails").update(inboundRecordId, { status: "FAILED" }).catch(() => {});
    return;
  }

  // Render DOCX → save to ./uploads (a normal library file).
  const buffer = await renderDocx(content, companyName);
  const onDiskName = `${nanoid()}.docx`;
  const safeTitle = content.title.replace(/[^a-z0-9 _-]/gi, "").trim() || "Draft";
  const originalName = `${safeTitle}.docx`;
  fs.writeFileSync(path.join(process.cwd(), "uploads", onDiskName), buffer);

  // 4c. Store in the Library (draft: true, source: email).
  let docId = "";
  try {
    const doc = await pb.collection("uploaded_documents").create({
      company: company.id,
      filename: onDiskName,
      originalName,
      contractType: DRAFT_TYPE_CONTRACTTYPE[draftType],
      status: "COMPLETE",
      counterpartyName: intentParams.counterparty ?? "",
      reviewType: "OUTBOUND",
      currency: "GBP",
      source: "email",
      draft: true,
    });
    docId = doc.id as string;
    await linkThreadContract(company.id as string, threadId, docId).catch(() => {});
  } catch (err) {
    console.error("[draft] could not store draft in library:", (err as Error)?.message);
  }

  // 4c (cont). Reply with the DOCX attached + a summary body. 4d footer included.
  const bullets = content.keyPositions.length > 0
    ? content.keyPositions
    : ["Built on your standard preferred positions for this document type."];
  const toConfirmNote = content.toConfirm.length > 0
    ? `Items needing your input are marked TO CONFIRM${content.toConfirm.length <= 6 ? `:\n${content.toConfirm.map((t) => `  • ${t}`).join("\n")}` : ` (${content.toConfirm.length} items in the document)`}.`
    : "Items needing your input are marked TO CONFIRM.";
  const reviewUrl = docId ? `${APP_URL}/review/${docId}` : "";

  // 3d: if the draft is for a known counterparty, pre-empt their likely pushback
  // as TO CONFIRM notes (advisory, these are NOT written into the draft text).
  const counterparty = (intentParams.counterparty ?? "").trim();
  const profile = counterparty
    ? await buildCounterpartyProfile(company.id as string, counterparty).catch(() => null)
    : null;
  const counterpartyToConfirm = profileDraftToConfirm(profile);
  const counterpartyNote = counterpartyToConfirm.length > 0
    ? `Likely pushback from ${counterparty}, TO CONFIRM before you send:\n${counterpartyToConfirm.map((t) => `  • ${t}`).join("\n")}`
    : "";

  const text =
    `First draft attached: ${content.title}.\n\n` +
    `Built on your playbook:\n${bullets.map((b) => `  • ${b}`).join("\n")}\n\n` +
    `${toConfirmNote}\n\n` +
    (counterpartyNote ? `${counterpartyNote}\n\n` : "") +
    (reviewUrl ? `Also saved to your Zane Library: ${reviewUrl}\n\n` : "") +
    `${FOOTER_TEXT(companyName)}`;

  const esc = (s: unknown) => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const html = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#FAFAF8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#FAFAF8;"><tr><td align="center">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;margin:32px auto;background:#fff;border:1px solid #E2E8F0;border-radius:12px;overflow:hidden;">
  <tr><td style="background:#0B1020;padding:20px 28px;"><span style="color:#fff;font-weight:700;font-size:16px;">Zane</span><span style="color:#94A3B8;font-size:11px;letter-spacing:0.08em;text-transform:uppercase;margin-left:8px;">First draft</span></td></tr>
  <tr><td style="padding:24px 28px 8px;">
    <div style="font-size:15px;color:#0B1020;font-weight:600;">First draft attached: ${esc(content.title)}</div>
    <div style="font-size:13px;color:#64748B;margin-top:6px;">Built on your playbook:</div>
    <ul style="margin:8px 0 0;padding-left:20px;color:#0B1020;font-size:14px;line-height:1.6;">
      ${bullets.map((b) => `<li>${esc(b)}</li>`).join("")}
    </ul>
  </td></tr>
  <tr><td style="padding:8px 28px;">
    <div style="font-size:13px;color:#475569;line-height:1.6;">${esc(toConfirmNote).replace(/\n/g, "<br>")}</div>
  </td></tr>
  ${counterpartyNote ? `<tr><td style="padding:8px 28px;">
    <div style="border:1px solid #E2E8F0;border-radius:10px;background:#F8FAFC;padding:14px 16px;">
      <div style="font-size:11px;font-weight:700;letter-spacing:0.08em;color:#64748B;text-transform:uppercase;margin-bottom:6px;">Counterparty intelligence</div>
      <div style="font-size:13px;color:#0B1020;line-height:1.6;">${esc(counterpartyNote).replace(/\n/g, "<br>")}</div>
    </div>
  </td></tr>` : ""}
  ${reviewUrl ? `<tr><td style="padding:16px 28px 8px;"><table role="presentation" cellpadding="0" cellspacing="0"><tr><td style="border-radius:8px;background:#2563EB;"><a href="${esc(reviewUrl)}" style="display:inline-block;padding:11px 20px;color:#fff;font-size:14px;font-weight:600;text-decoration:none;border-radius:8px;">Open in Zane Library →</a></td></tr></table></td></tr>` : ""}
  <tr><td style="padding:16px 28px;border-top:1px solid #E2E8F0;"><div style="font-size:11px;color:#94A3B8;line-height:1.5;">${esc(FOOTER_TEXT(companyName))}</div></td></tr>
</table></td></tr></table></body></html>`;

  await threadReplyHtml(ctx(docId || undefined), {
    to: sender, from: fromAddr, inReplyTo: messageId, subject: replySubject, html, text,
    attachments: [{ filename: originalName, content: buffer, contentType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" }],
  });

  void audit({
    action: "contract_uploaded",
    entityType: "uploaded_document",
    entityId: docId || undefined,
    companyId: company.id as string,
    detail: { source: "email", draft: true, draftType, sender },
  }).catch(() => {});

  if (inboundRecordId) await pb.collection("inbound_emails").update(inboundRecordId, { status: "DRAFT_SENT", intent: "draft_document" }).catch(() => {});
  console.log(`[draft] sent ${DRAFT_TYPE_LABEL[draftType]} → ${sender} (${content.clauses.length} clauses, ${content.toConfirm.length} TO CONFIRM)`);
}
