// Mock data used when the real database is empty or unavailable.
// Swap these out by replacing MOCK_MODE = false once real data flows in.

import type { UploadedDocument } from "./types";

export const MOCK_MODE = true;

// ─── Operational urgency signals ─────────────────────────────────────────────
// Shown in Dashboard urgency panel when in mock mode

export const MOCK_URGENCY_SIGNALS = [
  {
    id: "u1",
    type: "escalation" as const,
    severity: "red" as const,
    message: "3 unresolved escalations require GC sign-off",
    detail: "Acme Corp MSA · Enterprise Customer Agreement v3 · CloudVendor SaaS",
    docId: "mock-1",
  },
  {
    id: "u2",
    type: "threshold" as const,
    severity: "red" as const,
    message: "2 contracts exceed liability threshold",
    detail: "Liability caps set below 10% of contract value in both cases",
    docId: "mock-1",
  },
  {
    id: "u3",
    type: "renewal" as const,
    severity: "amber" as const,
    message: "Renewal notice due in 11 days — Acme Corp MSA",
    detail: "90-day notice period. Window closes 27 May 2026. Auto-renewal locks £420,000.",
    docId: "mock-1",
  },
  {
    id: "u4",
    type: "pattern" as const,
    severity: "amber" as const,
    message: "Counterparty deviation recurring across 4 agreements",
    detail: "Liability cap position unchanged across all Acme Corp reviews. Systemic pattern.",
    docId: "mock-1",
  },
];

// ─── Mock documents (dashboard list) ────────────────────────────────────────

export const MOCK_DOCUMENTS = [
  {
    id: "mock-1",
    originalName: "Acme Corp - Master Services Agreement.pdf",
    contractType: "MSA",
    status: "COMPLETE",
    uploadedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    counterpartyName: "Acme Corporation Ltd",
    counterpartyType: "CUSTOMER",
    contractValue: 420000,
    currency: "£",
    contractTermMonths: 36,
    autoRenewal: true,
    noticePeriodDays: 90,
    renewalDate: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    reviewResults: [
      { ragStatus: "RED",   escalationRequired: true  },
      { ragStatus: "RED",   escalationRequired: true  },
      { ragStatus: "AMBER", escalationRequired: false },
      { ragStatus: "AMBER", escalationRequired: false },
      { ragStatus: "AMBER", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREY",  escalationRequired: false },
    ],
    escalationRequired: true,
    signReadiness: "not-ready",
  },
  {
    id: "mock-2",
    originalName: "CloudVendor SaaS Subscription Agreement.pdf",
    contractType: "SUPPLIER_AGREEMENT",
    status: "COMPLETE",
    uploadedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    counterpartyName: "CloudVendor Technologies Ltd",
    counterpartyType: "TECH_VENDOR",
    contractValue: 84000,
    currency: "£",
    contractTermMonths: 12,
    autoRenewal: true,
    noticePeriodDays: 30,
    renewalDate: new Date(Date.now() + 65 * 24 * 60 * 60 * 1000).toISOString(),
    reviewResults: [
      { ragStatus: "RED",   escalationRequired: true  },
      { ragStatus: "AMBER", escalationRequired: false },
      { ragStatus: "AMBER", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
    ],
    escalationRequired: true,
    signReadiness: "negotiate",
  },
  {
    id: "mock-3",
    originalName: "TechPartners Data Processing Agreement.docx",
    contractType: "DPA",
    status: "COMPLETE",
    uploadedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    counterpartyName: "TechPartners Solutions Ltd",
    counterpartyType: "TECH_VENDOR",
    contractValue: 36000,
    currency: "£",
    contractTermMonths: 24,
    autoRenewal: false,
    renewalDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
    reviewResults: [
      { ragStatus: "AMBER", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREY",  escalationRequired: false },
    ],
    escalationRequired: false,
    signReadiness: "review",
  },
  {
    id: "mock-4",
    originalName: "GlobalSupply - Standard Vendor Contract.pdf",
    contractType: "SUPPLIER_AGREEMENT",
    status: "COMPLETE",
    uploadedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    counterpartyName: "GlobalSupply Ltd",
    counterpartyType: "SUPPLIER",
    contractValue: 210000,
    currency: "£",
    contractTermMonths: 24,
    autoRenewal: false,
    reviewResults: [
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "AMBER", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
    ],
    escalationRequired: false,
    signReadiness: "ready",
  },
  {
    id: "mock-5",
    originalName: "Series B Investor NDA - Term Sheet.pdf",
    contractType: "NDA",
    status: "PROCESSING",
    uploadedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    counterpartyName: "Redpoint Ventures IV LP",
    counterpartyType: "INVESTOR",
    reviewResults: [],
    escalationRequired: false,
    signReadiness: "pending",
  },
  {
    id: "mock-6",
    originalName: "Enterprise Customer Agreement v3.docx",
    contractType: "CUSTOMER_AGREEMENT",
    status: "COMPLETE",
    uploadedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    counterpartyName: "Meridian Financial Group plc",
    counterpartyType: "CUSTOMER",
    contractValue: 960000,
    currency: "£",
    contractTermMonths: 48,
    autoRenewal: true,
    noticePeriodDays: 90,
    renewalDate: new Date(Date.now() + 110 * 24 * 60 * 60 * 1000).toISOString(),
    reviewResults: [
      { ragStatus: "RED",   escalationRequired: true  },
      { ragStatus: "RED",   escalationRequired: true  },
      { ragStatus: "AMBER", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
      { ragStatus: "GREY",  escalationRequired: false },
      { ragStatus: "GREY",  escalationRequired: false },
      { ragStatus: "GREEN", escalationRequired: false },
    ],
    escalationRequired: true,
    signReadiness: "not-ready",
  },
];

// ─── Full mock review detail — Acme Corp MSA ─────────────────────────────────
// Shown when a user clicks mock-1 in demo mode.
// Typed as UploadedDocument so ReviewDetail can consume it directly.

export const MOCK_REVIEW_DETAIL: UploadedDocument = {
  id: "mock-1",
  companyId: "demo-company",
  filename: "acme-corp-msa.pdf",
  originalName: "Acme Corp - Master Services Agreement.pdf",
  contractType: "MSA",
  status: "COMPLETE",
  counterpartyName: "Acme Corporation Ltd",
  counterpartyType: "CUSTOMER",
  contractValue: 420000,
  currency: "£",
  contractTermMonths: 36,
  autoRenewal: true,
  noticePeriodDays: 90,
  renewalDate: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
  uploadedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  reviewResults: [
    {
      id: "rr-1",
      documentId: "mock-1",
      clauseCategory: "LIABILITY_CAP",
      ragStatus: "RED",
      isAbsent: false,
      escalationRequired: true,
      escalationTrigger: "Liability cap set at 1 month of fees (£35,000) — hard red line requires 12 months minimum (£420,000). GC sign-off mandatory before proceeding.",
      clauseSummary: "Clause 12.3 limits Acme Corp's aggregate liability to fees paid in the preceding calendar month. No carve-outs exist for data breaches, wilful misconduct, or death and personal injury beyond statutory minima.",
      whyItMatters: "A 1-month cap on a £420,000 annual contract means your maximum recovery in a catastrophic failure scenario is £35,000 — less than 10% of contract value. This creates severe asymmetric risk, particularly given the data processing and SaaS obligations under this agreement.",
      recommendedAction: "Push back to 12-month aggregate liability cap (£420,000) with explicit carve-outs for: (i) data breach under UK GDPR, (ii) wilful misconduct or gross negligence, (iii) IP indemnity claims. This is a hard red line — do not sign until revised.",
      suggestedFallback: "The aggregate liability of each party to the other under or in connection with this Agreement shall not exceed an amount equal to twelve (12) months' Fees paid or payable in the twelve months preceding the event giving rise to the claim, except that this limit shall not apply to (i) either party's indemnification obligations under clause 14, (ii) death or personal injury caused by negligence, (iii) fraud or wilful misconduct, or (iv) any liability which cannot be excluded by applicable law.",
      businessSummary: "Acme are capping their liability at one month's fees — £35k on a £420k deal. If their platform fails and you suffer loss, you're almost certainly undercompensated. This clause needs to change before signing.",
      confidenceLabel: "HIGH",
      comparisonStatement: "CONTRACT: 1 calendar month fee cap (~£35,000)\nPLAYBOOK REQUIRED: 12-month minimum cap (~£420,000)\nGAP: 11 months / £385,000 shortfall\nSTATUS: Hard red line breach — GC escalation mandatory",
      regulatoryCitations: [
        { regulation: "Unfair Contract Terms Act 1977", article: "s.2(2)", relevance: "Exclusion of liability for negligence causing financial loss is void unless reasonable under the circumstances." },
        { regulation: "UK GDPR", article: "Art. 82", relevance: "Data processor liability for GDPR breaches cannot be wholly excluded by contract. Carve-out from liability cap is required." },
      ],
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "rr-2",
      documentId: "mock-1",
      clauseCategory: "INDEMNITY",
      ragStatus: "RED",
      isAbsent: false,
      escalationRequired: true,
      escalationTrigger: "Indemnity structure is asymmetric — your obligations are uncapped while Acme's are subject to the general liability cap. GC review required before execution.",
      clauseSummary: "Clause 14.1 requires you to indemnify Acme Corp against all claims arising from breach of warranty, IP infringement, or data protection obligations. Acme's reciprocal indemnity in clause 14.2 is limited to third-party IP claims only and subject to the general liability cap.",
      whyItMatters: "You bear an uncapped indemnity obligation covering warranty breach and data processing failures. Acme's indemnity to you is capped and far narrower. This creates significant asymmetric exposure — particularly in a data incident scenario where you are the data processor.",
      recommendedAction: "Negotiate mutual indemnities on equivalent terms. Your data protection indemnity must be subject to your standard liability cap except for wilful breach. Acme's indemnity should extend to their own data processing failures.",
      suggestedFallback: "Each party ('Indemnifying Party') shall indemnify the other party ('Indemnified Party') against all direct losses, claims and reasonable legal costs arising from any third-party claim that the Indemnifying Party's material breach of this Agreement caused. Each party's indemnity obligation shall be subject to the aggregate liability cap in clause 12.3, except where the loss arises from wilful misconduct or fraud.",
      businessSummary: "You have an open-ended duty to compensate Acme for almost any breach. They owe you a much narrower duty, with a cap on top. This structural imbalance needs correcting before signing.",
      confidenceLabel: "HIGH",
      comparisonStatement: "CONTRACT: Your obligations uncapped, Acme's capped and narrowly scoped to IP claims only\nPLAYBOOK REQUIRED: Mutual indemnities on equivalent terms, both subject to the same liability cap\nSTATUS: Red — structural asymmetry requires negotiation",
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "rr-3",
      documentId: "mock-1",
      clauseCategory: "DATA_PRIVACY",
      ragStatus: "AMBER",
      isAbsent: false,
      escalationRequired: false,
      clauseSummary: "Clause 18 contains data processing obligations broadly compliant with UK GDPR. However, the Data Processing Schedule lacks specific sub-processor notification timelines, and breach notification runs from Acme's discovery rather than yours as processor.",
      whyItMatters: "UK GDPR Article 33(2) requires processors to notify controllers without undue delay upon becoming aware of a breach. The current drafting shifts this trigger to Acme's discovery, which could expose you if Acme is slow to investigate or disclose internally.",
      recommendedAction: "Amend breach notification trigger to run from processor's (your) discovery. Require sub-processor list at signing, updated with 10 business days' written notice of any changes.",
      suggestedFallback: "The Processor shall notify the Controller without undue delay, and in any event within 72 hours of the Processor becoming aware of a Personal Data Breach affecting Controller Personal Data.",
      businessSummary: "The data terms are largely acceptable but the breach notification timing creates regulatory risk. A straightforward fix — amend the trigger date and you're compliant.",
      confidenceLabel: "HIGH",
      comparisonStatement: "CONTRACT: 72-hour notification from Controller's (Acme's) discovery\nPLAYBOOK REQUIRED: 72-hour notification from Processor's (your) discovery\nSTATUS: Amber — breach trigger timing requires amendment",
      regulatoryCitations: [
        { regulation: "UK GDPR", article: "Art. 33(2)", relevance: "Processor must notify controller without undue delay after becoming aware of a personal data breach — trigger must run from processor's knowledge." },
      ],
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "rr-4",
      documentId: "mock-1",
      clauseCategory: "AUTO_RENEWAL",
      ragStatus: "AMBER",
      isAbsent: false,
      escalationRequired: false,
      clauseSummary: "Clause 7.2 provides for automatic annual renewal unless either party gives 90 days' written notice before the renewal date. The renewal date is 15 June 2026. The 90-day notice window closes 17 March 2026.",
      whyItMatters: "Failure to give notice by 17 March 2026 commits you to a further 12 months at £420,000. Given this value, renewal decisions require board-level input with adequate lead time — the 90-day window is already narrower than your standard 120-day planning cycle.",
      recommendedAction: "Log the renewal notice deadline (17 March 2026) in your contract management system immediately. Set a calendar reminder 120 days prior (~17 November 2025) to begin renewal assessment. Consider negotiating the notice period down to 60 days or adding a notification obligation from Acme.",
      businessSummary: "Auto-renewal is active. Miss the 90-day notice window and you're locked in for another year at £420,000. The window is already open — add this deadline to your calendar today.",
      confidenceLabel: "HIGH",
      suggestedFallback: "",
      comparisonStatement: "CONTRACT: Auto-renewal on 90-day notice, window closes 17 March 2026\nPLAYBOOK: Renewal notices logged 120 days in advance for contracts over £100,000\nSTATUS: Amber — renewal notice due sooner than standard planning cycle",
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "rr-5",
      documentId: "mock-1",
      clauseCategory: "TERMINATION",
      ragStatus: "AMBER",
      isAbsent: false,
      escalationRequired: false,
      clauseSummary: "Clause 15 permits termination for cause on 30 days' written notice with opportunity to cure. Termination for convenience requires 6 months' written notice. No termination right exists for material adverse change, regulatory change, or sustained service level failure.",
      whyItMatters: "A 6-month notice period for termination for convenience is double the market standard for MSAs of this size (typically 3 months). You have no clean exit if performance is consistently poor, creating lock-in risk during sustained underperformance.",
      recommendedAction: "Negotiate termination for convenience to 3 months. Add a termination right for sustained SLA failure: if service availability falls below 99.5% for 2 consecutive months, you should have the right to terminate on 30 days' notice without early termination charge.",
      suggestedFallback: "Either party may terminate this Agreement for convenience on not less than three (3) months' prior written notice. In addition, the Customer may terminate on 30 days' written notice if the Service fails to meet the Service Level commitments for two (2) or more consecutive calendar months.",
      businessSummary: "You're locked in for 6 months' notice to leave — twice the market standard. And if the service is consistently poor, you have no clean exit. Both points need negotiating.",
      confidenceLabel: "HIGH",
      comparisonStatement: "CONTRACT: 6-month notice for termination for convenience\nPLAYBOOK REQUIRED: Maximum 3 months for contracts under £500,000\nSTATUS: Amber — above market standard, negotiate reduction",
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "rr-6",
      documentId: "mock-1",
      clauseCategory: "IP_OWNERSHIP",
      ragStatus: "GREEN",
      isAbsent: false,
      escalationRequired: false,
      clauseSummary: "Clause 9 clearly establishes that all pre-existing IP is retained by its owner. Deliverables created specifically for you are assigned on payment in full. Background IP used in deliverables is licensed on a perpetual, royalty-free, non-exclusive basis.",
      whyItMatters: "IP allocation is clearly structured. The perpetual licence for background IP ensures you retain access to deliverables after termination. Assignment conditional on payment in full is commercially standard and protects both parties.",
      recommendedAction: "Accept as drafted. Verify that the definition of 'Deliverables' in Schedule 1 covers all expected outputs before signing.",
      suggestedFallback: "",
      businessSummary: "IP ownership is clean and well-structured. You own what's built for you, you can keep using their tools indefinitely, and their rights are clearly bounded. No changes needed.",
      confidenceLabel: "HIGH",
      comparisonStatement: "CONTRACT: Clean IP assignment for bespoke work, perpetual licence for background IP\nPLAYBOOK REQUIRED: Assignment of deliverables, perpetual licence for tools\nSTATUS: Green — consistent with playbook",
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "rr-7",
      documentId: "mock-1",
      clauseCategory: "CONFIDENTIALITY",
      ragStatus: "GREEN",
      isAbsent: false,
      escalationRequired: false,
      clauseSummary: "Clause 10 establishes mutual confidentiality obligations with a 5-year survival term post-termination. Standard carve-outs for publicly available information, prior knowledge, and independent development. Disclosure to legal and regulatory authorities permitted with prior written notice where legally permissible.",
      whyItMatters: "The 5-year survival term exceeds your playbook minimum of 3 years. Mutual obligations are symmetrical and the carve-outs are standard and reasonable. No concerns.",
      recommendedAction: "Accept as drafted.",
      suggestedFallback: "",
      businessSummary: "Strong confidentiality terms — 5-year mutual obligations, clean carve-outs, appropriate scope. No changes needed.",
      confidenceLabel: "HIGH",
      comparisonStatement: "CONTRACT: 5-year mutual confidentiality, standard carve-outs\nPLAYBOOK REQUIRED: Minimum 3 years, mutual obligations\nSTATUS: Green — exceeds minimum requirements",
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "rr-8",
      documentId: "mock-1",
      clauseCategory: "PAYMENT_TERMS",
      ragStatus: "GREEN",
      isAbsent: false,
      escalationRequired: false,
      clauseSummary: "Clause 6 sets payment at 30 days from invoice. Annual fees are invoiced quarterly in advance. Price escalation is capped at CPI+2% per year from Year 2. Interest on overdue amounts accrues at 4% above Bank of England base rate.",
      whyItMatters: "Payment terms are commercially standard. The CPI+2% escalation cap provides cost predictability over the 36-month term. Quarterly advance invoicing is typical for MSA/SaaS arrangements of this size.",
      recommendedAction: "Accept the payment structure. Consider whether CPI+2% creates excessive exposure in high-inflation years — you may want an absolute annual cap (e.g., maximum 5% increase). Confirm the late payment interest direction applies to amounts owed by Acme.",
      suggestedFallback: "",
      businessSummary: "Payment terms are fair and standard. Quarterly in advance is typical, the escalation cap gives you price predictability, and 30-day payment is market standard. Minor clarification on interest direction recommended.",
      confidenceLabel: "HIGH",
      comparisonStatement: "CONTRACT: 30-day payment, quarterly advance invoicing, CPI+2% escalation\nPLAYBOOK REQUIRED: Maximum 30-day terms, escalation cap preferred\nSTATUS: Green — consistent with playbook",
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "rr-9",
      documentId: "mock-1",
      clauseCategory: "GOVERNING_LAW",
      ragStatus: "GREEN",
      isAbsent: false,
      escalationRequired: false,
      clauseSummary: "Clause 22 specifies English and Welsh law as governing law with exclusive jurisdiction of the courts of England and Wales.",
      whyItMatters: "English law is your preferred governing law. Exclusive English jurisdiction is appropriate for a UK-domiciled counterparty. No concerns.",
      recommendedAction: "Accept as drafted.",
      suggestedFallback: "",
      businessSummary: "English law, English courts — exactly what your playbook requires. Accept.",
      confidenceLabel: "HIGH",
      comparisonStatement: "CONTRACT: English and Welsh law, exclusive English jurisdiction\nPLAYBOOK REQUIRED: English law preferred\nSTATUS: Green — matches playbook",
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "rr-10",
      documentId: "mock-1",
      clauseCategory: "INSURANCE",
      ragStatus: "GREY",
      isAbsent: true,
      escalationRequired: false,
      clauseSummary: "No insurance obligation clause was identified in this agreement.",
      whyItMatters: "Your playbook requires counterparties to maintain Professional Indemnity (minimum £1m per claim), Public Liability (minimum £2m), and Cyber / Data Breach cover (minimum £500k). Without this clause, you have no contractual basis to require evidence of coverage or direct recourse against their insurer.",
      recommendedAction: "Request insertion of an insurance clause. Require Acme Corp to maintain: (i) Professional Indemnity: minimum £1,000,000 per claim; (ii) Public Liability: minimum £2,000,000; (iii) Cyber / Data Breach: minimum £500,000. Certificates of currency to be provided on request and annually.",
      suggestedFallback: "Each party shall maintain throughout the term: (a) Professional Indemnity insurance of not less than £1,000,000 per claim; (b) Public Liability insurance of not less than £2,000,000; and (c) Cyber Liability and Data Breach insurance of not less than £500,000. Evidence of such coverage shall be provided to the other party within 10 Business Days of written request.",
      businessSummary: "No insurance obligation was included. If Acme causes you loss and is uninsured, you're limited to their balance sheet. This clause is missing and should be added before signing.",
      confidenceLabel: "HIGH",
      comparisonStatement: "CONTRACT: No insurance clause present\nPLAYBOOK REQUIRED: PI £1m+, PL £2m+, Cyber £500k+\nSTATUS: Absent — clause missing, must be added",
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
};

// ─── Existing mock stats & portfolio data ────────────────────────────────────

export const MOCK_STATS = {
  totalReviews: 14,
  totalDocuments: 16,
  redFlagsOpen: 8,
  escalationsPending: 3,
  clausesAccepted: 37,
  estimatedHoursSaved: 21,
  ragBreakdown: { RED: 18, AMBER: 34, GREEN: 72, GREY: 12 },
  topIssues: [
    { category: "LIABILITY_CAP", count: 9 },
    { category: "DATA_PRIVACY", count: 6 },
    { category: "AUTO_RENEWAL", count: 4 },
  ],
};

export const MOCK_PORTFOLIO_RISK = {
  categories: [
    { label: "Insurance & Indemnity", red: 5, amber: 8, green: 12, icon: "🛡️" },
    { label: "Liability & Warranties", red: 7, amber: 11, green: 9, icon: "⚖️" },
    { label: "Data & Privacy",         red: 3, amber: 6,  green: 16, icon: "🔐" },
    { label: "Termination & Renewal",  red: 2, amber: 9,  green: 14, icon: "📅" },
  ],
  topRedCategories: [
    { category: "LIABILITY_CAP",   count: 9, pct: 90 },
    { category: "INDEMNITY",       count: 7, pct: 70 },
    { category: "DATA_PRIVACY",    count: 5, pct: 50 },
    { category: "INSURANCE",       count: 4, pct: 40 },
    { category: "TERMINATION",     count: 3, pct: 30 },
  ],
  byContractType: [
    { type: "Master Services Agreement", red: 4, amber: 5, total: 3 },
    { type: "Supplier Agreement",        red: 6, amber: 9, total: 5 },
    { type: "Customer Agreement",        red: 3, amber: 4, total: 3 },
    { type: "NDA",                       red: 0, amber: 2, total: 2 },
    { type: "Data Processing Agreement", red: 1, amber: 3, total: 2 },
  ],
  insight: "Liability caps are your most contested issue — counterparties are consistently pushing for 1-3 month fee caps vs your required 12-month minimum. Consider whether your commercial risk appetite for MSAs and Supplier Agreements needs recalibration.",
};

export const MOCK_RENEWALS = {
  upcoming: [
    {
      id: "r1",
      contractName: "Acme Corp - Master Services Agreement",
      eventType: "Auto-renewal deadline",
      date: "17 Mar 2026",
      daysUntil: 28,
      noticePeriod: "90 days",
      actionRequired: true,
    },
    {
      id: "r2",
      contractName: "CloudVendor SaaS Subscription",
      eventType: "Contract expiry",
      date: "30 Jun 2026",
      daysUntil: 65,
      noticePeriod: "30 days",
      actionRequired: false,
    },
    {
      id: "r3",
      contractName: "GlobalSupply Vendor Contract",
      eventType: "Renewal notice deadline",
      date: "1 Aug 2026",
      daysUntil: 93,
      noticePeriod: "90 days",
      actionRequired: false,
    },
    {
      id: "r4",
      contractName: "Enterprise Customer Agreement v3",
      eventType: "Annual review date",
      date: "15 Sep 2026",
      daysUntil: 110,
      noticePeriod: "45 days",
      actionRequired: false,
    },
    {
      id: "r5",
      contractName: "TechPartners DPA",
      eventType: "Contract expiry",
      date: "31 Dec 2026",
      daysUntil: 228,
      noticePeriod: "60 days",
      actionRequired: false,
    },
  ],
  termOverview: [
    { label: "Expiring within 30 days",   count: 1, pct: 10 },
    { label: "Expiring within 90 days",   count: 2, pct: 20 },
    { label: "Expiring within 12 months", count: 5, pct: 50 },
    { label: "Long-term (12m+)",          count: 5, pct: 50 },
  ],
};

export const MOCK_ACTIONS = [
  {
    id: "a1",
    docId: "mock-1",
    docName: "Acme Corp - Master Services Agreement",
    type: "escalation" as const,
    message: "Liability cap breaches red line — GC sign-off required",
    ragStatus: "RED",
  },
  {
    id: "a2",
    docId: "mock-6",
    docName: "Enterprise Customer Agreement v3",
    type: "escalation" as const,
    message: "Uncapped indemnity clause requires Board approval",
    ragStatus: "RED",
  },
  {
    id: "a3",
    docId: "mock-1",
    docName: "Acme Corp - Master Services Agreement",
    type: "review" as const,
    message: "3 AMBER clauses awaiting your decision",
    ragStatus: "AMBER",
  },
  {
    id: "a4",
    docId: "mock-2",
    docName: "CloudVendor SaaS Subscription Agreement",
    type: "review" as const,
    message: "Data privacy clause needs push-back before signing",
    ragStatus: "AMBER",
  },
];
